import Vue from "vue";
import VueRouter from "vue-router";
import Home from "../views/Home.vue";
import SearchResults from "../views/SearchResults.vue";
import MealDetail from "../views/MealDetail.vue";

Vue.use(VueRouter);

// A list of views, each associated with a path.
// The router will look at the current path (e.g. /meal/4) and render the first matching
// route whose `path` matches the url.
// See https://stackoverflow.com/a/10473302/7742560 for a brief explanation of Client Side Routing.
// TODO: define remaining routes.
const routes = [
  {
    // The `:id` will automagically read the remaining part of the url and
    // assign it to a variable stored under `$route.params.id`.
    // For example, if we enter /meal/5, id will be set to 5.
    path: "/meal/:id",
    name: "MealDetail",
    component: MealDetail,
  },
  {
    path: "/search-results/",
    name: "SearchResults",
    component: SearchResults,
  },
  {
    path: "/",
    name: "Home",
    component: Home,
  },
];

// Some vue-router boilerplate.
// NOTE(zajonc): to be honest, I don't really know what this bit does. It's been autogenerated.
const router = new VueRouter({
  mode: "history",
  base: process.env.BASE_URL,
  routes,
});

export default router;
